import type { Metadata } from "next";
import "./globals.css";
import { AppProviders }  from './providers'

export const metadata: Metadata = {
  title: "Tibiki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className="antialiased">
        <AppProviders>
        {children}
        </AppProviders>
      </body>
    </html>
  );
}
