import type { Metadata } from 'next';

import './globals.css';

import React from 'react';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Keep root layout as a server component boundary; client providers are applied in segment layouts.
  return children;
}
